import { React,useEffect,useState } from "react"
import { Cards,FormField,Loader } from "../Components"


const RenderCards = ({data,title}) => 
{
  if(data?.length > 0)
  {
    return data.map( (post) => { <Cards key = {post.id} {...post}/> })
  }
  return(
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">
      {title}
    </h2>
  )
}

export default function Home() {
  let [loading,setloading] = useState(false);
  let [allPosts,setAllPost] = useState(null);
  let [searchText,setSearchText] = useState("");
  return (
    <section className="max-w=7xl mx-auto">
            <div>
              <h1 className="font-extrabold text-[#222328] text-[32px]">
                The Company Show Case
              </h1>
              <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
                Browse through a collection of imagiation and visually stunning images generated by Dall-E
              </p>
            </div>

            <div className="mt-16">
                <FormField/>
            </div>

            <div className="mt-10">
                {
                  loading?(
                  <div className="flex justify-center items-center">
                  <Loader/>  
                  </div> ):
                  (
                  <>
                     {searchText&&(
                      <h2 className="font-medium text-[#666e75] text-xlmb-3">
                          Showing result for <span className="text-[#222328]"> {searchText} </span>
                      </h2>
                     )}
                     <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                      {
                        searchText?<RenderCards data={{}} title="No Result Found"/>:
                        <RenderCards data={{}} title="No posts Found"/>
                      }
                     </div>
                  </>
                  )
                }
            </div>
    </section>
  )
}
